### ISSUE TITLE
Rails did not install (Windows version)

### ISSUE THREAD

**Issue by VodenBlack** [jhu-ep-coursera/fullstack-course1-module1#15]
I ran the specified rails package installer 'railsinstaller-3.2.0.exe' and everything seemed to install fine. However when I did the recommended command line actions to check the versions, only GIT and Ruby installed. Rails commands are not recognized.
![image](https://cloud.githubusercontent.com/assets/24212198/20651662/140a7946-b49e-11e6-995e-ace58228a34f.png)

**Comment by ejavaguy** [comment]
Did you run the following to install rails ? (last two options are not
required)

gem install rails -v 4.2.6 --no-ri --no-doc

**Comment by VodenBlack** [comment]
Yes. This is what I get back:

![image](https://cloud.githubusercontent.com/assets/24212198/20651790/6ef33486-b4a0-11e6-8cc8-72afce285c56.png)

**Comment by ejavaguy** [comment]
https://github.com/jhu-ep-coursera/fullstack-course1-module1/wiki#q-what-to-do-when-rails-fails-to-update

Be sure to follow the SSL solution and not the alternate non-SSL work-around
https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by VodenBlack** [comment]
When I click on the link 'AddTrustExternalCARoot-2048.pem' I get an error 404: Not Found.
Should I go ahead and do the non-SSL work around then?

**Comment by ejavaguy** [comment]
Hmm. Seems like Kalman needs to reference a different page. I found this
one to have the same content but with reliable links

http://guides.rubygems.org/ssl-certificate-update/#background


This is the link they reference -- make sure it gets stored as PEM
format/suffix and not a TXT format/suffix.

https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/index.rubygems.org/GlobalSignRootCA.pem

**Comment by kalmanh** [comment]
Thank you @ejavaguy - I updated the wiki with the updated URL. What is wrong with the non-SSL workaround?

**Comment by ejavaguy** [comment]
> What is wrong with the non-SSL workaround?
@kalman - SSL provides a level of trust verification that we are getting
our gems from a trusted source (trusted == at least who they say they are)

**Comment by VodenBlack** [comment]
Thanks for the help. I think I now have all of the tools responding with version numbers. However, now running the final check of Rails I get this error:

![image](https://cloud.githubusercontent.com/assets/24212198/20680661/d235f7a4-b554-11e6-9c6b-d696f55edf3c.png)

**Comment by kalman** [comment]
wrong kalman, please remove me from CC

**Comment by kalmanh** [comment]
Yes, I am the REAL Kalman and he is not! :)

I am first (my first name is Kalman) and he is last (his last name is Kalman)

**Comment by kalman** [comment]
Hah. Also I found the "unsubscribe" button.

So long as the correct Kalman is involved, I'm happy.

**Comment by kalmanh** [comment]
@VodenBlack as for the actual error - you need to install NodeJs. The error you are getting is a variation of https://github.com/jhu-ep-coursera/fullstack-course1-module1/wiki#q-how-to-fix-the-execjsprogramerror

**Comment by kalmanh** [comment]
@kalman - I like your puppy... wait, is that a sheep? a horse? ;)

**Comment by kalman** [comment]
It's a goat, and it's sadly not mine.

Best of luck getting Rails to install on Windows, though :-)
