### ISSUE TITLE
Localhost:3000

### ISSUE THREAD

**Issue by zakcreate** [jhu-ep-coursera/fullstack-course1-module1#19]
It says site can not be reached. Not sure what yet wrong. Recommendations on what I should check?

I did:
$ rails new test_app
$ rails server

Doesn't work.

**Comment by bacala** [comment]
Doesn't work ?
Did you get something like:
```
=> Booting WEBrick
=> Rails 4.2.3 application starting in development on http://0.0.0.0:9023
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
```
or you didn't get anything ?

BR

**Comment by zakcreate** [comment]
I get this:[image: Inline image 1]

Zachary Allen Kravits

UX Designer & Fine Artist

Linkedin: Linkedin Profile
<https://www.linkedin.com/in/zachary-allen-kravits-119b3a58>

**Comment by zakcreate** [comment]
​after trying to run rails server I get this:
[image: Inline image 1]​

I have also tried running "bundle install" but that also gives an error


Zachary Allen Kravits

UX Designer & Fine Artist

Linkedin: Linkedin Profile
<https://www.linkedin.com/in/zachary-allen-kravits-119b3a58>

**Comment by zakcreate** [comment]
when i use the most recent version of ruby and rails, the server works. However, when I try using the older version that is suggested then it says
Run `bundle install` to install missing gems.
Once I run bundle install, I get this:
ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the
current version, ruby 2.2.3p173

**Comment by zakcreate** [comment]
On a mac

**Comment by RenaudQC** [comment]
@bacala I'm getting what you wrote with 5.1 version. Does this mean that it works? Thanks !

**Comment by sams3pi** [comment]
I am getting this
Booting WEBrick
=> Rails 4.2.3 application starting in development on http://0.0.0.0:9023
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server

**Comment by bacala** [comment]
Yes, for me it works with that output. You should try to access the web server, than you will have more output.
