### ISSUE TITLE
Error installing Rails on Windows

### ISSUE THREAD

**Issue by tomefavre** [jhu-ep-coursera/fullstack-course1-module1#22]
Hi guys, I don't know what is the problem:

![image](https://user-images.githubusercontent.com/7844403/32509083-7688bfb6-c3d3-11e7-92e4-e4c9b9a2f114.png)

**Comment by yhlee123** [comment]
Seems good to me. What is your issue here?

**Comment by kalmanh** [comment]
For anyone else facing this issue - install Node.js (https://nodejs.org/en/) and then restart your computer and try again
