### ISSUE TITLE
railsinstaller.org link does not work

### ISSUE THREAD

**Issue by 1CodingGirl** [jhu-ep-coursera/fullstack-course1-module1#23]
I am trying to install ruby, rails and git via the provided link at railsinstaller.org.  Link does not seem to be working.

**Comment by bxmadministrator** [comment]
Try http://railsinstaller.org/en

**Comment by bassamabed** [comment]
Try http://railsinstaller.org/en

**Comment by grisreyesrios** [comment]
Thanks for the suggestion. Actually, the link that you suggest is the only one that works to install all the packages for the specialization.

**Comment by emmanuelajaero** [comment]
https://s3.amazonaws.com/railsinstaller/Windows/railsinstaller-3.4.0.exe

you can download it from the link
