### ISSUE TITLE
Ruby Past End of Life

### ISSUE THREAD

**Issue by mgbvox** [jhu-ep-coursera/fullstack-course1-module1#24]
This is on an iMac High Sierra, ca 2018.

When running 'rbenv install 2.2.3' in the Terminal I get:

'WARNING: ruby-2.2.3 is past its end of life and is now unsupported.

It no longer receives bug fixes or critical security updates.'

Presumably this means we should be using a newer version of ruby. What version should we use, if any? What is the correct terminal command to use? And can y'all update the installation git?

**Comment by prusswan** [comment]
Try Ruby 2.2.8. You can also try Ruby 2.4.x but I am not sure if the course
materials have been updated to support it, it should not require too much
changes however.

**Comment by kalmanh** [comment]
2.2.8 and 2.4 should both be fine for the course
