### ISSUE TITLE
botsnap issue

### ISSUE THREAD

**Issue by rebecacll** [jhu-ep-coursera/fullstack-course1-module1#25]
I am receiving an issue when creating the first test file, it says:

An error occurred while installing bootsnap (1.4.2), and Bundler cannot
continue.
Make sure that `gem install bootsnap -v '1.4.2' --source
'https://rubygems.org/'` succeeds before bundling.

**Comment by Leganeren** [comment]
Similar problem, but mine is with the sqlite3 1.4.1

**Comment by kalmanh** [comment]
https://github.com/jhu-ep-coursera/fullstack-course1-module3/wiki#q-sqlite-error
