### ISSUE TITLE
install phantomjs fails in MacOSX El Capitan (10.11.1)

### ISSUE THREAD

**Issue by Valer11** [jhu-ep-coursera/fullstack-course1-module1#8]
`$ brew install phantomjs`

will fail with error if you are using MacOSX El Capitan

`$ brew install phantomjs
phantomjs: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.`

To fix it just do https://github.com/Homebrew/homebrew/issues/44535#issuecomment-155671155

**Comment by kalmanh** [comment]
Thank you for reporting this. Check out the answer on the wiki https://github.com/jhu-ep-coursera/fullstack-course1-module1/wiki#q-how-to-install-phantomjs-on-osx-el-capitan

**Comment by Valer11** [comment]
Thank you. It worked. But I still have phantomjs 1.9.8. How can I update it
to ver 2?

**Comment by kalmanh** [comment]
Version 1.9.8 is all you need.
